### PR TITLE
Sort available coins to show preference for age

### PR DESCRIPTION
**Pull request by dantudor**

### CODE REVIEW

**Comment by mxaddict** [comment]
utACK

**Comment by mxaddict** [comment]
I think the code change looks fine, it should work almost the same as original functionality.

only difference is now the old inputs get staked first.

**Comment by mxaddict** [comment]
@dantudor you plan on merging these upstream?

**Comment by dantudor** [comment]
Do you think it adds value outside of pool staking?

Alex suggested I merge changes upstream as it will help me stay aligned to
the code in core and make pull downs easier.

**Comment by mxaddict** [comment]
It might add value to other people wanting to run pools.

And if you add a setting to turn it on and have it off by default it should be fine to have in core.

**Pull request merged**
